apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-converter
  namespace: log-converter
  labels:
    app: log-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-converter
  template:
    metadata:
      labels:
        app: log-converter
    spec:
      containers:
      - name: log-converter
        image: log-converter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        volumeMounts:
        - name: logging-storage
          mountPath: /app/logging
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: logging-storage
        persistentVolumeClaim:
          claimName: log-converter-storage
