apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-converter-storage
  namespace: log-converter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
