apiVersion: v1
kind: Service
metadata:
  name: log-converter
  namespace: log-converter
  labels:
    app: log-converter
spec:
  type: NodePort
  selector:
    app: log-converter
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
    nodePort: 30300
